# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anxiety Driven Development
email: anxietydrivendevelopment@gmail.com
description: >
  A software development blog written by an anxious programmer.
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  anxietydrivendevelopment

# Build settings
markdown: kramdown
